name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  qa:
    name: Quality Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@1.4.0
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
